refactor the elasticsearch.yaml some along with some additional envir…
DataDog/upstream-helm-charts pull request #1
Opened 2018-07-16 18:47 UTC by platinummonkey

**What this PR does / why we need it:**
We wanted some more flexibility on the runtime options for ElasticSearch. Mostly refactors elasticsearch.yml into it's own template as a number of additional settings were added.

This will support 1.x line if custom images are provided.

**Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):**

fixes #

**Special notes for your reviewer:**

This is still a WIP, trying to get some quick feedback.

2018-07-16 19:09 UTC, pietdaniel requested changes
This PR does a lot, can we split into smaller functional components.

2018-07-16 19:09 UTC, pietdaniel commented on incubator/elasticsearch/README.md
> +| `cluster.routing_attributes`         | Cluster routing attributes                                          | `nil`                                |
this should be camel cased to be consistent

2018-07-16 19:09 UTC, pietdaniel commented on incubator/elasticsearch/README.md
> +| `client.java.opts_equal`             | Client node java `-<key>=<value>` options                           | `{}`                                 |
this should be camel cased to be consistent

2018-07-16 19:09 UTC, pietdaniel commented on incubator/elasticsearch/README.md
> +| `data.java.opts_equal`               | Data node java `-<key>=<value>` options                             | `{}`                                 |
this should be camel cased to be consistent

2018-07-16 19:09 UTC, pietdaniel commented on incubator/elasticsearch/README.md
> +| `master.java.opts_equal`             | Master node java `-<key>=<value>` options                           | `{}`                                 |
this should be camel cased to be consistent

2018-07-16 19:21 UTC, platinummonkey commented
Updated title and message to reflect this PR is not meant to be merged, but to flush out ideas. Later smaller PR's will be created to make this more digestible.

2018-07-18 13:50 UTC, platinummonkey commented
@pietdaniel to take the lead! closing this

2018-07-18 13:50 UTC, closed without merging